Calculator:Milestone-2
jebitok-dev/calculator pull request #2
Opened 2021-06-02 16:44 UTC by jebitok-dev

In this milestone I:-
- created the components Display, ButtonPanel, with buttons then linked them to the main App component.
- made a basic layout of the calculator app
- ensured the app live version is up

2021-06-02 19:57 UTC, trekab requested changes
### Changes Required! :recycle: 
Hi @jebitok-dev! So far so good! :+1: There just a few changes for you to make to complete this milestone. These include:
- [ ] Place the `App` component in the `src/components` directory ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/App.png))
- [ ] `App`'s children components should be wrapped in [React.Fragment](https://reactjs.org/docs/fragments.html#short-syntax) short syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/ReactFragment.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896092/))
- [ ] Your `ButtonPanel` component should include __all__ the following buttons divided in the groups below: ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/buttonPanel/buttons.png))
  * Group 1: AC, +/-, %, ÷
  * Group 2: 7, 8, 9, X
  * Group 3: 4, 5, 6, -
  * Group 4: 1, 2, 3, +
  * Group 5: 0, ., =

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__[Treasure Kabareebe](https://trekab.github.io)__

2021-06-03 04:15 UTC, afanimartin requested changes
### Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work making the requested changes.
Let's however make one more change before merging.
- Add the `X` button to the `ButtonDisplay` component.

### Martin Afani
#### Slack: whiz25

2021-06-03 04:15 UTC, afanimartin commented on src/components/buttonPanel.js
> +            {this.renderButton('÷')}
- This group is lacking the `X` button. This was already pointed out. Carefully review comments by TSEs.

2021-06-03 05:21 UTC, afanimartin approved these changes
## Approved 👏🏿 👏🏿 👏🏿 
Nice work making the requested changes. Merge and proceed to the next milestone.

### Martin Afani
#### Slack: whiz25

2021-06-03 05:43 UTC, merged